# Generated by Django 3.1.3 on 2020-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='donation.Category'),
        ),
    ]
