# Generated by Django 3.1.3 on 2020-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-pick_up_date']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
